import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeroThemeProvider from "./providers";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Turfi",
  description: "Generated by create next app",
icons: {
  icon: [
    { url: "/favicon.png", type: "image/png" }
  ],
},
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <HeroThemeProvider>
          {/* <Navbar></Navbar> */}
          {children}
        </HeroThemeProvider>
        <Footer></Footer>
        <Toaster />
      </body>
    </html>
  );
}
