import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeroThemeProvider from "./providers";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <HeroThemeProvider>
          <Navbar></Navbar>
          {children}
        </HeroThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
